### ISSUE TITLE
iOS中 disabled颜色太不明显

### ISSUE THREAD

**Issue by zhouzhongyuan** [BokeFE/QA#6]
#### 进入方式

门店管理——终端拜访（选今天）——门店抄单——点击物料后在跳出的查询条件输个100——随便勾选一个物料确定——规格/当前库存/单位/订单金额 都是不可编辑，颜色是灰色的

**Comment by zhouzhongyuan** [comment]
### 用时: 2h

### 时间: 8:30-10:30

### 解决：顾老师用时1分钟解决

### 表现形式: input的color在Chrome中正常，Safari中颜色非常淡

### 原因:

这个input中包含disabled。不同浏览器对disabled的解析是不一样的。Safari中对disabled的解析是改变其color，但是不是通过改变opacity的方式。

### 解决方案：

``` css
input[type="text"]:disabled {
    -webkit-text-fill-color: #9E9E9E;
}
```

### 感慨：
- 我用了1h58m 没有解决这个问题，顾老师用了1分钟解决了。
- 经验很重要啊
- 应该系统学习一下css了
